# Generated by Django 5.1.5 on 2025-01-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'task1_delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.DecimalField(decimal_places=0, max_digits=12)),
                ('age_limited', models.BooleanField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'task1_deliverydet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'task1_vendor',
                'managed': False,
            },
        ),
    ]
